//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int id { get; set; }
        public string name { get; set; }
        public string title { get; set; }
        public Nullable<decimal> price { get; set; }
        public string logDescription { get; set; }
        public string shortDescription { get; set; }
        public string qrcode { get; set; }
        public string imageURL { get; set; }
    }
}
